# Generated by Django 3.2.9 on 2021-12-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='announcementattributevalue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
