# Generated by Django 3.2.9 on 2021-12-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211206_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='announcementattributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
