# Generated by Django 3.2.9 on 2021-12-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'managed': False},
        ),
    ]
